SEARCH_DIR("/lib/x86_64-linux-gnu/")
SEARCH_DIR("/usr/lib/x86_64-linux-gnu/")
SEARCH_DIR("/lib64/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib64/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/11/")
SEARCH_DIR("./")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/lcl/units/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/components/freetype/lib/x86_64-linux/")
SEARCH_DIR("/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/lazarus/packager/units/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/httpd22/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gdbint/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/sqlite/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/cdrom/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/zorba/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-hash/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/chm/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/symbolic/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libcurl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/wasmtime/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ldap/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/regexpr/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/tcl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/httpd24/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/oracle/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libgd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pastojs/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libusb/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libvlc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libmagic/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/openssl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/bfd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-unicode/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/hash/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libfontconfig/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/mysql/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gtk1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/bzip2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/utils-pas2js/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libcups/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/modplug/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ibase/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/a52/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/openal/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opencl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fftw/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/wasmedge/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libpng/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/tplylib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/uuid/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/users/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fpindexer/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-pdf/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/numlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/odbc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/lua/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/mad/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/hermes/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/jni/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/sdl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gmp/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libgc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-mustache/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/zlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/dts/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libpcre/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libenet/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pthreads/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libffi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libxml2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/testinsight/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/graph/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gnome1/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ncurses/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/webidl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/syslog/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/imlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libmicrohttpd/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libsee/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opengles/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libnettle/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/xforms/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gnutls/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/libtar/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/postgres/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/cairo/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/utmp/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/dblib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/paszlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fppkg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/dbus/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gitlab/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/newt/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/proj4/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/aspell/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pxlib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fv/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/svgalib/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/googleapi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/odata/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ptc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/x11/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/vcl-compat/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/opengl/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-css/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-report/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/ggi/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rsvg/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/unzip/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/pcap/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gdbm/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/gst/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/")
SEARCH_DIR("/home/tux/fpcupdeluxe_trunk/fpc/bin/x86_64-linux/")
INPUT(
/lib/x86_64-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/11/crtbeginS.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/si_c.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/abitag.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/SDL_OpenGL_33/lib/x86_64-linux/Project1.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/system.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/lnfodwrf.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/exeinfo.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/strings.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/objpas.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/ctypes.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_main.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_mutex.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_scancode.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_keycode.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_events.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_messagebox.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_surface.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_version.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_stdinc.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_rect.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_assert.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_error.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_init.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_timer.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_video.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_opengl.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_opengl_glext.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/SDL_OpenGL_33/lib/x86_64-linux/oglvector.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/SDL_OpenGL_33/lib/x86_64-linux/oglshader.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/unixtype.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_keyboard.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_mouse.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_joystick.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_audio.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_camera.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_touch.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_pen.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_sensor.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_pixels.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_properties.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_rwops.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_blendmode.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/packages/lib/x86_64-linux/sdl3_guid.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/classes.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/sysutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/fileutil.o
/n4800/DATEN/Programmierung/mit_GIT/Lazarus/Tutorial/SDL-2/sdl3/SDL_OpenGL_33/lib/x86_64-linux/ogldebug.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/types.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/typinfo.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/rtlconsts.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/sortbase.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/linux.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/baseunix.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/unix.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/errors.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/sysconst.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/unixutil.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/math.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/strutils.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/masks.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazutf8.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazfileutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/contnrs.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazutilsstrconsts.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/cwstring.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/fpcadds.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/initc.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/dynlibs.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/unixcp.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/dl.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/translations.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/jsonscanner.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/jsonparser.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/fpjson.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lconvencoding.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazloggerbase.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/avglvltree.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/stringhashlist.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-json/jsonreader.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/variants.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl-objpas/varutils.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/rtl/dos.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/codepagescommon.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/codepagesasian.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazclasses.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazmethodlist.o
/home/tux/fpcupdeluxe_trunk/fpc/units/x86_64-linux/fcl-base/avl_tree.o
/home/tux/fpcupdeluxe_trunk/lazarus/components/lazutils/lib/x86_64-linux/lazdbglog.o
)
INPUT(
-lSDL3
-ldl
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-linux-gnu/11/crtendS.o
/lib/x86_64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
